development:
 database: devise-demo
 adapter: postgresql
 username: postgres
 password: 12345678
 host: localhost
 pool: 5
 timeout: 5000


production:
 adapter: postgresql
 encoding: unicode
 database: devise-demo
 pool: 5
 username: postgres
 password: 12345678
